#!/bin/bash

# Check if a commandline argument was given
if [ -z "$1" ]; then
	echo "No projectname given"
	exit
fi

# VARIABLES
USERNAME=daniel
PROJECT_NAME=$1
WWW_DIR=/home/$USERNAME/Web/www
NEW_DIR=$WWW_DIR/$PROJECT_NAME
NEW_URL=http://$PROJECT_NAME.dev
HOSTS_FILE=/home/$USERNAME/Web/configfiles/hosts
VIRTUAL_HOSTS_FILE=/home/$USERNAME/Web/configfiles/000-default.conf

# FUNCTIONS
function runasuser {
	sudo -u ${USERNAME} -H sh -c "cd $NEW_DIR; $1"
}

function announce {
	sleep 1
	echo "-- $1 --"
	sleep 1
}

# WORK
announce "CREATING NEW LARAVEL PROJECT AT $WWW_DIR/$PROJECT_NAME"
sudo -u ${USERNAME} -H sh -c "cd $WWW_DIR; /home/$USERNAME/.composer/vendor/bin/laravel new $PROJECT_NAME; cd $PROJECT_NAME"

cd $NEW_DIR

announce "RUNNING COMPOSER INSTALL"
composer install

announce "RUNNING NPM INSTALL"
npm install
npm uninstall gulp --save
npm install grunt --save
npm install grunt-contrib-watch --save
npm install grunt-contrib-sass --save

announce "MOVING .env"
mv .env.example .env

announce "GENERATING PROJECT KEY"
runasuser "php artisan key:generate"


announce "CREATING DIRS AND SETTING PERMISSIONS"
runasuser "mkdir public/uploads; mkdir public/media;mkdir public/media/css;mkdir public/media/imgs;mkdir public/media/fonts; mkdir public/media/components"
runasuser "mkdir public/media/js; touch public/media/js/global.js"
runasuser "mkdir public/media/sass; touch public/media/sass/global.scss"
runasuser "mkdir resources/templates; touch resources/templates/default.blade.php; mkdir resources/pages; touch resources/pages/index.blade.php"

announce "ADDING VIRTUALHOST TO APACHE"
cat <<EOT >> $VIRTUAL_HOSTS_FILE

<VirtualHost *:80>
	ServerName www.$PROJECT_NAME.dev
	ServerAlias $PROJECT_NAME.dev
	DocumentRoot $NEW_DIR/public
</VirtualHost>
EOT

announce "RESTARTING APACHE"
service apache2 restart

announce "ADDING $PROJECT_NAME.dev TO HOSTS FILE"
echo "" >> $HOSTS_FILE
echo "127.0.0.1	$PROJECT_NAME.dev" >> $HOSTS_FILE

announce "CREATING .bowerrc"
touch .bowerrc
cat <<EOT >> .bowerrc
{
	"directory":"public/media/components",
	"analytics":false
}
EOT

announce "CREATING bower.json"
touch bower.json
cat <<EOT >> bower.json
{
  "name": "$PROJECT_NAME",
  "version":"0.0.1",
  "homepage":"https://github.com/Sakto",
  "authors": ["Daniel <saktomail@gmail.com>"],
  "moduleType": ["amd"],
  "license":"MIT",
  "private":true,
  "ignore": [
    "**/.*",
    "node_modules",
    "public/media/components",
    "bower_components",
    "public/media/components",
    "test",
    "tests",
    "tags"
  ]
}
EOT

announce "ADDING STUFF TO .gitignore"
cat <<EOT >> .gitignore

/bower_components
/public/media/components
/public/uploads
tags
EOT

announce "RUNNING CTAGS"
ctags -R .

announce "REMOVING REDUNDANT FILES AND ADDING readme.md"
rm gulpfile.js
rm readme.md
touch readme.md
echo ""

announce "STARTING GIT REPO"
runasuser "git init"

announce "UPDATING PERMISSIONS"
chmod -R 777 storage
chmod -R 775 bootstrap/cache
chmod -R 775 public/uploads
cd ..
chown -R $USERNAME:www-data $PROJECT_NAME

announce "AND HERE WE GO!"
runasuser "nemo $NEW_DIR"
runasuser "gnome-terminal $NEW_DIR"
runasuser "gvim .env readme.md app/Http/routes.php"
runasuser "xdg-open $NEW_URL"

